# Generated by Django 2.1.3 on 2019-03-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
