# Generated by Django 2.1.3 on 2019-03-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profile_picture',
        ),
    ]
