# Generated by Django 2.2.1 on 2019-05-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20190519_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
